### ISSUE TITLE
Conta é encerrada sempre

### ISSUE THREAD

**Issue by di3g0rb** [jeymson/conta-bancaria-poo#2]
https://github.com/jeymson/conta-bancaria-poo/blob/14e5e8670b6e126024d1f62adfa174a6405675b7/Aula05/src/aula05/Conta.java#L49

**Comment by jeymson** [comment]
Correção liberada.
Nova versão disponível para download. 
Recomendamos a todos os nossos clientes que atualizem para a nova versão por motivos de segurança.
